services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - hardhat

  hardhat:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.hardhat
    container_name: hardhat
    ports:
      - "8545:8545"
    volumes:
      - ./hardhat:/hardhat

    
