# Hardhat Dockerfile
FROM node:20-alpine
WORKDIR /hardhat
COPY hardhat/package.json ./
COPY hardhat/package-lock.json ./
COPY hardhat/contracts ./contracts
COPY hardhat/scripts ./scripts
COPY hardhat/test ./test
RUN npm install --legacy-peer-deps
EXPOSE 8545
CMD ["npx", "hardhat", "node", "--hostname", "0.0.0.0"]
