# ZKsync Local Node Dockerfile (not needed if using official image)
# If you want to build your own, see https://github.com/matter-labs/local-node
# For most users, the official image in docker-compose is sufficient.
FROM matterlabs/local-node:latest
